language: r

r_github_packages:
    - jimhester/covr

r_binary_packages:
    - covr
    - testthat
    - knitr

before_script:
    - curl -L -O https://raw.githubusercontent.com/mllg/travis-r-tools/master/update-packages.r
    - Rscript update-packages.r

after_success:
    - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always
