language: r

r_github_packages:
    - jimhester/covr

r_binary_packages:
    - testthat
    - knitr

before_script:
    - git clone https://github.com/mllg/travis-r-tools.git travis-r-tools
    - Rscript travis-r-tools/update-packages.r

after_success:
    - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always
