language: r

r_github_packages:
    - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always
